### ISSUE TITLE
static files issue (more than one admin interface)

### ISSUE THREAD

**Issue by PeterKharchenko** [Alexmod/flask-security-flask-admin-mongodb#2]
In the scenario where there are more than one admin interfaces (assuming access to those interfaces is supposed to be provided to non-admin users), static files are still fetched from /admin/static/, and the following line of code in "app/views/members_views.py" denies access:
"if request.path.startswith('/admin')"

**Comment by Alexmod** [comment]
In this case use is_accessible
http://flask-admin.readthedocs.io/en/latest/api/mod_base/

```python
class MyModelView(ModelView):

    def is_accessible(self):
        if not current_user.is_active or not current_user.is_authenticated:
            return False

        if current_user.has_role('superuser'):
            return True

        return False
```

and remove "if request.path.startswith('/admin') from before request.

**Comment by PeterKharchenko** [comment]
thanks - i think in this case it is also necessary to define is_accessible for AdminIndexView and specify index_view when creating Admin object 

```
class SecuredAdminIndexView(AdminIndexView):
    def __init__(self,*args,**kwargs):
        super(SecuredAdminIndexView,self).__init__(*args,**kwargs)
    def is_accessible(self):    
        if current_user.has_role("admin"):return True
        else:return False
admin = Admin(app, template_mode='bootstrap3',index_view =SecuredAdminIndexView(url='/admin',endpoint='admin'))
```
